### ISSUE TITLE
Multiple errors in App

### ISSUE THREAD

**Issue by brofey** [HighCoordination/trueChart-Menubar4Sense#3] opened 2018-02-27 08:22 UTC
Hi, i've got 5 different buttons, with many actions which works perfectly in QlikView.

Qlik Sense server version is February 2018

I tried to make same buttons in this extension, and they work in the same way, but sometimes there appeares an error popup window in app with sign: "An error has occurred. Invalid parameters"

Also there thousands of errors in Developer Tools console while button actions are performed (about 150 erros per button click):
```
client.js?1515426796317:1 Error from Engine: {jsonrpc: "2.0", id: 5026, error: {…}}
client.js?1515426796317:1 Error from Engine: {jsonrpc: "2.0", id: 5027, error: {…}}
client.js?1515426796317:1 Error from Engine: {jsonrpc: "2.0", id: 5028, error: {…}}
client.js?1515426796317:1 Error from Engine: {jsonrpc: "2.0", id: 5029, error: {…}}
client.js?1515426796317:1 Error from Engine: {jsonrpc: "2.0", id: 5043, error: {…}}
```

Button has SEQUENTAL actions:
1. Lock field "Type"
2. Clear all
3. Select value in field "Month" value=month(Today()) with mode Toggle
4. Select value in field "Year" value=Year(Today()) with mode Toggle
5. Unlock all.

All actions are performed correctly, but console logs are full of errors, and sometimes error window appears.

Tried to use 3 and 4 actions without Toggle mode, got same actions.

Why does "An error has occurred. Invalid parameters" popup window appear?

P.S. Great extension!

**Comment by HighCoordination** [comment] 2018-03-05 12:34
@brofey 

**No trueChart Menubar bug**
Thanks for your report. The problem you are describing has to do with the general functionality of the Sense Engine and is "unfortunately" not a bug in the menu bar.

**How the Sense Engine Works**
All actions are sent via a socket interface (Engine API). In particular, actions in connection with selections lead to a so-called invalidation of the data model. This means that all actions sent to the engine in the meantime are automatically terminated because the model is no longer valid. Each of these aborts is logged with an error from engine. So far it is "normal". 
However, if these terminations occur too often, since many actions are carried out one after the other, the Sense Engine may assume an error and return the error message you have described.

**Solution / Workaround**
The only way to avoid this is to either use fewer selection-related actions within a button or to run these actions in parallel instead of sequentially. In the button action Configuration there is a corresponding icon button on the right side of each action. Please check if in your case all actions are marked as parallel.

Best regards
Stefan

**Closed** 2018-03-05 12:35 UTC
Labels: sense engine
